import os
import json
import numpy as np
from ollama import Client
from datetime import datetime
from tqdm import tqdm
from sklearn.model_selection import train_test_split

class FeedbackReinforcementLearning:
    """
    A class to implement reinforcement learning for the assignment feedback system.
    This collects manual feedback from instructors and uses it to improve the LLM.
    """
    
    def __init__(self, config_file="config/reinforcement_config.json"):
        """Initialize the reinforcement learning module"""
        self.config = self._load_config(config_file)
        self.feedback_store = self._load_feedback_store()
        
        # Initialize Ollama client
        try:
            self.ollama_client = Client()
            print("✅ Connected to Ollama service")
        except Exception as e:
            print(f"⚠️ Error connecting to Ollama: {e}")
            self.ollama_client = None
        
        # Create necessary directories
        os.makedirs(self.config["feedback_data_dir"], exist_ok=True)
        os.makedirs(self.config["fine_tuning_dir"], exist_ok=True)
    
    def _load_config(self, config_file):
        """Load configuration from JSON file"""
        default_config = {
            "feedback_data_dir": "./data/feedback_reinforcement/",
            "feedback_store_file": "./data/feedback_reinforcement/feedback_store.json",
            "fine_tuning_dir": "./data/fine_tuning/",
            "ollama_model": "codellama:13b",
            "min_samples_for_fine_tuning": 20,
            "learning_rate": 5e-5,
            "epochs": 3,
            "batch_size": 4
        }
        
        try:
            if os.path.exists(config_file):
                with open(config_file, "r") as f:
                    config = json.load(f)
                # Merge with defaults
                for key, value in default_config.items():
                    if key not in config:
                        config[key] = value
                return config
            else:
                print(f"⚠️ Config file {config_file} not found. Using default configuration.")
                return default_config
        except Exception as e:
            print(f"⚠️ Error loading config: {e}. Using default configuration.")
            return default_config
    
    def _load_feedback_store(self):
        """Load the feedback store from disk"""
        if os.path.exists(self.config["feedback_store_file"]):
            try:
                with open(self.config["feedback_store_file"], "r") as f:
                    return json.load(f)
            except Exception as e:
                print(f"⚠️ Error loading feedback store: {e}. Creating new store.")
                return {"feedback_pairs": [], "metadata": {"last_updated": None}}
        else:
            return {"feedback_pairs": [], "metadata": {"last_updated": None}}
    
    def _save_feedback_store(self):
        """Save the feedback store to disk"""
        try:
            # Update metadata
            self.feedback_store["metadata"]["last_updated"] = datetime.now().isoformat()
            
            # Ensure directory exists
            os.makedirs(os.path.dirname(self.config["feedback_store_file"]), exist_ok=True)
            
            # Save the feedback store
            with open(self.config["feedback_store_file"], "w") as f:
                json.dump(self.feedback_store, f, indent=2)
            print(f"✅ Feedback store saved with {len(self.feedback_store['feedback_pairs'])} entries")
        except Exception as e:
            print(f"⚠️ Error saving feedback store: {e}")
    
    def store_feedback_pair(self, submission_id, original_code, model_feedback, 
                          instructor_feedback, instructor_rating, feedback_meta=None):
        """
        Store a new feedback pair for future fine-tuning
        
        Args:
            submission_id (str): Identifier for the submission
            original_code (str): The original Java code submission
            model_feedback (str): Feedback generated by the model
            instructor_feedback (str): Corrected feedback from instructor
            instructor_rating (float): Rating from 0-1 (how good was the model's feedback)
            feedback_meta (dict): Additional metadata about the feedback
        """
        # Create a feedback entry
        feedback_entry = {
            "submission_id": submission_id,
            "timestamp": datetime.now().isoformat(),
            "original_code": original_code,
            "model_feedback": model_feedback,
            "instructor_feedback": instructor_feedback,
            "instructor_rating": float(instructor_rating),
            "meta": feedback_meta if feedback_meta else {}
        }
        
        # Check if an entry with this submission_id already exists
        for i, entry in enumerate(self.feedback_store["feedback_pairs"]):
            if entry["submission_id"] == submission_id:
                # Update the existing entry
                self.feedback_store["feedback_pairs"][i] = feedback_entry
                self._save_feedback_store()
                return
        
        # Add the new entry if it doesn't exist
        self.feedback_store["feedback_pairs"].append(feedback_entry)
        self._save_feedback_store()
    
    def prepare_fine_tuning_data(self):
        """
        Prepare and format the collected feedback data for fine-tuning
        
        Returns:
            dict: Statistics about the prepared data
        """
        if len(self.feedback_store["feedback_pairs"]) < self.config["min_samples_for_fine_tuning"]:
            print(f"⚠️ Not enough samples for fine-tuning. Need at least {self.config['min_samples_for_fine_tuning']}.")
            return {
                "status": "insufficient_data",
                "samples_needed": self.config["min_samples_for_fine_tuning"],
                "samples_available": len(self.feedback_store["feedback_pairs"])
            }
        
        # Prepare the training and validation datasets
        train_data, val_data = train_test_split(
            self.feedback_store["feedback_pairs"], 
            test_size=0.2,
            random_state=42
        )
        
        # Format data for fine-tuning
        formatted_train_data = self._format_data_for_fine_tuning(train_data)
        formatted_val_data = self._format_data_for_fine_tuning(val_data)
        
        # Save the formatted data
        train_file = os.path.join(self.config["fine_tuning_dir"], "train.jsonl")
        val_file = os.path.join(self.config["fine_tuning_dir"], "val.jsonl")
        
        with open(train_file, "w") as f:
            for item in formatted_train_data:
                f.write(json.dumps(item) + "\n")
                
        with open(val_file, "w") as f:
            for item in formatted_val_data:
                f.write(json.dumps(item) + "\n")
        
        return {
            "status": "success",
            "training_samples": len(formatted_train_data),
            "validation_samples": len(formatted_val_data),
            "train_file": train_file,
            "val_file": val_file
        }
    
    def _format_data_for_fine_tuning(self, feedback_pairs):
        """
        Format the feedback pairs for fine-tuning the model
        
        Args:
            feedback_pairs (list): List of feedback pair entries
            
        Returns:
            list: Formatted data for fine-tuning
        """
        formatted_data = []
        
        for pair in feedback_pairs:
            # Create a prompt-completion pair for fine-tuning
            formatted_entry = {
                "messages": [
                    {
                        "role": "system",
                        "content": "You are an expert Java instructor evaluating code submissions for SOLID principles. Provide clear, specific, and actionable feedback."
                    },
                    {
                        "role": "user",
                        "content": f"Analyze this Java code for SOLID principles and provide feedback:\n\n```java\n{pair['original_code']}\n```"
                    },
                    {
                        "role": "assistant",
                        "content": pair["instructor_feedback"]  # Use the instructor's feedback as the target
                    }
                ]
            }
            formatted_data.append(formatted_entry)
        
        return formatted_data
    
    def fine_tune_model(self):
        """
        Fine-tune the LLM using collected feedback data
        Note: This is a placeholder for Ollama fine-tuning functionality
        In practice, you would need to use a platform that supports fine-tuning
        """
        # This is a placeholder for actual fine-tuning implementation
        # Fine-tuning with Ollama requires additional setup or external tools
        
        print("⚠️ Fine-tuning for local Ollama models requires additional steps:")
        print("1. Export your data from the prepare_fine_tuning_data() method")
        print("2. Use tools like 'lora-fine-tuning' to fine-tune the model")
        print("3. Import the fine-tuned model back into Ollama")
        
        # Return placeholder for future implementation
        return {
            "status": "not_implemented",
            "message": "Direct fine-tuning for Ollama models requires external tools. See documentation for implementation details."
        }
    
    def evaluate_improvements(self, test_submissions):
        """
        Evaluate the improvements in feedback quality after fine-tuning
        
        Args:
            test_submissions (list): List of test submissions to evaluate
            
        Returns:
            dict: Evaluation results
        """
        if self.ollama_client is None:
            return {"status": "error", "message": "Ollama client not initialized"}
        
        results = {
            "before_fine_tuning": [],
            "after_fine_tuning": [],
            "instructor_ratings": []
        }
        
        # Get some feedback pairs that weren't used in training
        eval_pairs = self.feedback_store["feedback_pairs"][-5:] if len(self.feedback_store["feedback_pairs"]) >= 5 else []
        
        if not eval_pairs:
            return {"status": "error", "message": "No evaluation data available"}
        
        for pair in tqdm(eval_pairs, desc="Evaluating model improvements"):
            # Get original feedback (before fine-tuning)
            original_feedback = pair["model_feedback"]
            
            # Get instructor feedback (ground truth)
            instructor_feedback = pair["instructor_feedback"]
            
            # Get feedback from potentially fine-tuned model
            try:
                # Generate feedback with current model
                response = self.ollama_client.generate(
                    model=self.config["ollama_model"],
                    prompt=f"Analyze this Java code for SOLID principles and provide feedback:\n\n```java\n{pair['original_code']}\n```"
                )
                new_feedback = response['response']
                
                # Store results
                results["before_fine_tuning"].append(original_feedback)
                results["after_fine_tuning"].append(new_feedback)
                results["instructor_ratings"].append(pair["instructor_rating"])
                
            except Exception as e:
                print(f"⚠️ Error generating feedback: {e}")
        
        # Calculate metrics
        if results["before_fine_tuning"]:
            # Add simple metrics here (would need more complex metrics in practice)
            # This is just a placeholder for demonstration purposes
            results["metrics"] = {
                "samples_evaluated": len(results["before_fine_tuning"]),
                "avg_instructor_rating": np.mean(results["instructor_ratings"]),
            }
        
        return results
    
    def get_learning_stats(self):
        """Get statistics on the learning progress"""
        if not self.feedback_store["feedback_pairs"]:
            return {
                "status": "no_data",
                "message": "No feedback data collected yet"
            }
        
        # Calculate statistics
        ratings = [pair["instructor_rating"] for pair in self.feedback_store["feedback_pairs"]]
        timestamps = [datetime.fromisoformat(pair["timestamp"]) for pair in self.feedback_store["feedback_pairs"]]
        
        # Sort by timestamp
        sorted_data = sorted(zip(timestamps, ratings), key=lambda x: x[0])
        sorted_timestamps, sorted_ratings = zip(*sorted_data)
        
        # Calculate moving average if there's enough data
        window_size = 5
        if len(sorted_ratings) >= window_size:
            moving_avg = [
                np.mean(sorted_ratings[i:i+window_size]) 
                for i in range(len(sorted_ratings) - window_size + 1)
            ]
        else:
            moving_avg = [np.mean(sorted_ratings)]
        
        return {
            "status": "success",
            "total_samples": len(self.feedback_store["feedback_pairs"]),
            "avg_rating": np.mean(ratings),
            "median_rating": np.median(ratings),
            "min_rating": min(ratings),
            "max_rating": max(ratings),
            "recent_trend": "improving" if len(moving_avg) > 1 and moving_avg[-1] > moving_avg[0] else "stable",
            "timestamps": [ts.isoformat() for ts in sorted_timestamps],
            "ratings": sorted_ratings,
            "moving_avg": moving_avg,
            "samples_needed_for_training": max(0, self.config["min_samples_for_fine_tuning"] - len(ratings))
        }


# Example usage
if __name__ == "__main__":
    rl = FeedbackReinforcementLearning()
    
    # Example of storing feedback
    rl.store_feedback_pair(
        submission_id="student123",
        original_code="public class User { void saveUser() {} void sendEmail() {} }",
        model_feedback="The User class violates SRP by handling both persistence and notification.",
        instructor_feedback="The User class violates the Single Responsibility Principle by handling both user persistence (saveUser method) and notification (sendEmail method). These should be separated into two distinct classes: User and EmailService.",
        instructor_rating=0.6,
        feedback_meta={"violation_type": "SRP"}
    )
    
    # Check learning stats
    stats = rl.get_learning_stats()
    print(f"Learning stats: {json.dumps(stats, indent=2)}")
    
    # Prepare data for fine-tuning (will likely show insufficient data in this example)
    prep_stats = rl.prepare_fine_tuning_data()
    print(f"Preparation stats: {json.dumps(prep_stats, indent=2)}")