"""
Simplified implementation of Reinforcement Learning from Human Feedback (RLHF)

This module handles the collection of instructor feedback and
generation of improved feedback using a simple exemplar-based approach.
"""

import os
import json
import numpy as np
from datetime import datetime
from ollama import Client

class FeedbackReinforcementLearning:
    """
    A simplified class to implement reinforcement learning for the assignment feedback system.
    This collects manual feedback from instructors and uses it to improve feedback generation.
    """
    
    def __init__(self, config_file="config/reinforcement_config.json"):
        """Initialize the reinforcement learning module"""
        self.config = self._load_config(config_file)
        self.feedback_store = self._load_feedback_store()
        
        # Initialize Ollama client
        try:
            self.ollama_client = Client()
            print("✅ Connected to Ollama service")
        except Exception as e:
            print(f"⚠️ Error connecting to Ollama: {e}")
            self.ollama_client = None
        
        # Create necessary directories
        os.makedirs(self.config["feedback_data_dir"], exist_ok=True)
    
    def _load_config(self, config_file):
        """Load configuration from JSON file"""
        default_config = {
            "feedback_data_dir": "./data/feedback_reinforcement/",
            "feedback_store_file": "./data/feedback_reinforcement/feedback_store.json",
            "ollama_model": "codellama:13b",
            "min_samples_for_improvement": 3,
            "top_examples_to_use": 2
        }
        
        try:
            if os.path.exists(config_file):
                with open(config_file, "r") as f:
                    config = json.load(f)
                # Merge with defaults
                for key, value in default_config.items():
                    if key not in config:
                        config[key] = value
                return config
            else:
                print(f"⚠️ Config file {config_file} not found. Using default configuration.")
                return default_config
        except Exception as e:
            print(f"⚠️ Error loading config: {e}. Using default configuration.")
            return default_config
    
    def _load_feedback_store(self):
        """Load the feedback store from disk"""
        if os.path.exists(self.config["feedback_store_file"]):
            try:
                with open(self.config["feedback_store_file"], "r") as f:
                    return json.load(f)
            except Exception as e:
                print(f"⚠️ Error loading feedback store: {e}. Creating new store.")
                return {"feedback_pairs": [], "metadata": {"last_updated": None}}
        else:
            return {"feedback_pairs": [], "metadata": {"last_updated": None}}
    
    def _save_feedback_store(self):
        """Save the feedback store to disk"""
        try:
            # Update metadata
            self.feedback_store["metadata"]["last_updated"] = datetime.now().isoformat()
            
            # Ensure directory exists
            os.makedirs(os.path.dirname(self.config["feedback_store_file"]), exist_ok=True)
            
            # Save the feedback store
            with open(self.config["feedback_store_file"], "w") as f:
                json.dump(self.feedback_store, f, indent=2)
            print(f"✅ Feedback store saved with {len(self.feedback_store['feedback_pairs'])} entries")
        except Exception as e:
            print(f"⚠️ Error saving feedback store: {e}")
    
    def store_feedback_pair(self, submission_id, original_code, model_feedback, 
                          instructor_feedback, instructor_rating, feedback_meta=None):
        """
        Store a new feedback pair for future improvement
        
        Args:
            submission_id (str): Identifier for the submission
            original_code (str): The original Java code submission
            model_feedback (str): Feedback generated by the model
            instructor_feedback (str): Corrected feedback from instructor
            instructor_rating (float): Rating from 0-1 (how good was the model's feedback)
            feedback_meta (dict): Additional metadata about the feedback
        """
        # Create a feedback entry
        feedback_entry = {
            "submission_id": submission_id,
            "timestamp": datetime.now().isoformat(),
            "original_code": original_code,
            "model_feedback": model_feedback,
            "instructor_feedback": instructor_feedback,
            "instructor_rating": float(instructor_rating),
            "meta": feedback_meta if feedback_meta else {}
        }
        
        # Check if an entry with this submission_id already exists
        for i, entry in enumerate(self.feedback_store["feedback_pairs"]):
            if entry["submission_id"] == submission_id:
                # Update the existing entry
                self.feedback_store["feedback_pairs"][i] = feedback_entry
                self._save_feedback_store()
                return
        
        # Add the new entry if it doesn't exist
        self.feedback_store["feedback_pairs"].append(feedback_entry)
        self._save_feedback_store()
    
    def get_top_examples(self, count=None):
        """
        Get the top-rated feedback examples to use as exemplars
        
        Args:
            count (int, optional): Number of examples to return
            
        Returns:
            list: Top-rated feedback examples
        """
        if count is None:
            count = self.config["top_examples_to_use"]
            
        # Sort feedback pairs by rating (highest first)
        sorted_pairs = sorted(
            self.feedback_store["feedback_pairs"],
            key=lambda x: x["instructor_rating"],
            reverse=True
        )
        
        # Return the top examples
        return sorted_pairs[:count]
    
    def generate_improved_feedback(self, code_snippet, detected_violations=None):
        """
        Generate improved feedback using exemplar-based approach
        
        Args:
            code_snippet (str): Code to analyze
            detected_violations (list, optional): Detected violations
            
        Returns:
            str: The improved feedback
        """
        if self.ollama_client is None:
            return "Error: Could not connect to Ollama service."
            
        # Check if we have enough examples
        if len(self.feedback_store["feedback_pairs"]) < self.config["min_samples_for_improvement"]:
            print(f"⚠️ Not enough feedback samples. Need at least {self.config['min_samples_for_improvement']}.")
            
            # Generate basic feedback without examples
            return self._generate_basic_feedback(code_snippet, detected_violations)
        
        # Get top examples to use
        top_examples = self.get_top_examples()
        
        # Format examples for the prompt
        examples_text = ""
        for i, example in enumerate(top_examples):
            examples_text += f"\nEXAMPLE {i+1}:\n"
            examples_text += f"INSTRUCTOR FEEDBACK:\n{example['instructor_feedback']}\n"
        
        # Format violations
        violations_text = ""
        if detected_violations:
            violations_text = "Detected violations:\n"
            for v in detected_violations:
                violations_text += f"- {v.get('principle', 'SOLID')}: {v.get('location', '')} - {v.get('description', '')}\n"
        
        # Create the prompt
        prompt = f"""
        You are an expert Java instructor evaluating code submissions for a SOLID principles refactoring assignment.
        
        Your goal is to provide clear, specific, and actionable feedback following these examples of high-quality instructor feedback:
        {examples_text}
        
        The student was required to complete these 5 refactoring steps:
        1. SRP Preparation: Split UserOperations into two interfaces
        2. SRP Implementation: Split RegularUserService into distinct services
        3. ISP & OCP: Split NotificationOperations using Strategy Pattern
        4. LSP: Fix AdminUser's deleteAccount method
        5. DIP: Create DatabaseDriver interface and use dependency injection

        Code to analyze:
        ```java
        {code_snippet}
        ```
        
        {violations_text}
        
        Format your response exactly as the examples above, clearly indicating:
        1. Overall assessment
        2. Status of each refactoring step (Fully implemented, Partially implemented, or Not implemented)
        3. Specific SOLID violations
        4. Concrete, actionable improvement suggestions
        """
        
        try:
            response = self.ollama_client.generate(
                model=self.config["ollama_model"],
                prompt=prompt
            )
            return response['response'].strip()
        except Exception as e:
            print(f"⚠️ Error generating feedback: {e}")
            return f"Error generating feedback: {str(e)}"
    
    def _generate_basic_feedback(self, code_snippet, detected_violations=None):
        """Generate basic feedback when not enough examples are available"""
        # Format violations
        violations_text = ""
        if detected_violations:
            violations_text = "Detected violations:\n"
            for v in detected_violations:
                violations_text += f"- {v.get('principle', 'SOLID')}: {v.get('location', '')} - {v.get('description', '')}\n"
        
        # Basic prompt without examples
        prompt = f"""
        You are an expert Java instructor evaluating code submissions for a SOLID principles refactoring assignment.
        
        The student was required to complete these 5 refactoring steps:
        1. SRP Preparation: Split UserOperations into two interfaces
        2. SRP Implementation: Split RegularUserService into distinct services
        3. ISP & OCP: Split NotificationOperations using Strategy Pattern
        4. LSP: Fix AdminUser's deleteAccount method
        5. DIP: Create DatabaseDriver interface and use dependency injection

        Code to analyze:
        ```java
        {code_snippet}
        ```
        
        {violations_text}
        
        Format your response with these sections:
        
        ## Overall Assessment
        [Brief assessment of implementation quality]

        ## Refactoring Steps Implementation
        [For each of the 5 steps, indicate completion status]

        ## SOLID Violations
        [List only violations related to the required refactoring steps]

        ## Improvement Suggestions
        [Provide specific, actionable code changes]
        """
        
        try:
            response = self.ollama_client.generate(
                model=self.config["ollama_model"],
                prompt=prompt
            )
            return response['response'].strip()
        except Exception as e:
            print(f"⚠️ Error generating basic feedback: {e}")
            return f"Error generating feedback: {str(e)}"
    
    def get_learning_stats(self):
        """Get statistics on the learning progress"""
        if not self.feedback_store["feedback_pairs"]:
            return {
                "status": "no_data",
                "message": "No feedback data collected yet"
            }
        
        # Calculate statistics
        ratings = [pair["instructor_rating"] for pair in self.feedback_store["feedback_pairs"]]
        timestamps = [datetime.fromisoformat(pair["timestamp"]) for pair in self.feedback_store["feedback_pairs"]]
        
        # Sort by timestamp
        sorted_data = sorted(zip(timestamps, ratings), key=lambda x: x[0])
        sorted_timestamps, sorted_ratings = zip(*sorted_data) if sorted_data else ([], [])
        
        # Calculate moving average if there's enough data
        window_size = min(3, len(sorted_ratings))
        if len(sorted_ratings) >= window_size:
            moving_avg = [
                np.mean(sorted_ratings[max(0, i-window_size+1):i+1]) 
                for i in range(len(sorted_ratings))
            ]
        else:
            moving_avg = [np.mean(sorted_ratings)] if sorted_ratings else []
        
        # Check if trend is improving
        trend = "improving"
        if len(moving_avg) >= 2:
            if moving_avg[-1] < moving_avg[0]:
                trend = "declining"
            elif abs(moving_avg[-1] - moving_avg[0]) < 0.05:
                trend = "stable"
        
        return {
            "status": "success",
            "total_samples": len(self.feedback_store["feedback_pairs"]),
            "avg_rating": np.mean(ratings) if ratings else 0,
            "median_rating": np.median(ratings) if ratings else 0,
            "min_rating": min(ratings) if ratings else 0,
            "max_rating": max(ratings) if ratings else 0,
            "recent_trend": trend,
            "timestamps": [ts.isoformat() for ts in sorted_timestamps],
            "ratings": sorted_ratings,
            "moving_avg": moving_avg,
            "samples_needed_for_improvement": max(0, self.config["min_samples_for_improvement"] - len(ratings))
        }