services:
  - type: web
    name: automated-assignment-feedback
    env: docker
    region: oregon
    plan: standard
    healthCheckPath: /
    disk:
      name: assignment-data
      mountPath: /app/data
      sizeGB: 20  # Increased size to accommodate all data files
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: GUNICORN_TIMEOUT
        value: "300"