services:
  - type: web
    name: automated-assignment-feedback
    env: docker
    region: oregon  # Choose a region close to your users
    plan: standard  # This is a paid plan that supports Docker
    healthCheckPath: /
    disk:
      name: assignment-data
      mountPath: /app/data
      sizeGB: 10
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "true"