services:
  - type: web
    name: automated-assignment-feedback
    env: docker
    region: oregon
    plan: standard
    healthCheckPath: /
    dockerfilePath: ./Dockerfile
    dockerContext: .
    disk:
      name: assignment-data
      mountPath: /app/data
      sizeGB: 20  # Increased size to accommodate all data files
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: GUNICORN_TIMEOUT
        value: "600"
      - key: OLLAMA_HOST
        value: http://ollama:11434
      - key: FLASK_SECRET_KEY
        generateValue: true  # Recommended for session security